# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: coins
          POSTGRES_PORT: 5432

    strategy:
      matrix:
        node-version: [16.13.2]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:

     - uses: actions/checkout@v3
#    - name: Use Node.js ${{ matrix.node-version }}
#      uses: actions/setup-node@v3
#      with:
#        node-version: ${{ matrix.node-version }}
#        cache: 'npm'
#    - run: npm install yarn -g
#    - run: yarn global add grunt
#    - run: yarn install
#    
#    - name: Create .env file for test environment
     - run: echo "$PWD" 
#    - run: npm run build --if-present
#    - run: cd test && grunt test
